from sqlite3 import *

def DBSetUp():
    file = connect("Test.db")
    cs = file.cursor()

    cs.execute("""CREATE TABLE IF NOT EXISTS LightWright
    (
    Purpose TEXT,
    Channel TEXT PRIMARY KEY,
    Dimmer TEXT,
    Address TEXT,
    Position TEXT,
    Unit# TEXT,
    Instrument Type TEXT,
    Load TEXT,
    Accessory TEXT,
    Color TEXT,
    Gobo TEXT,
    Gobo Size TEXT,
    Cicuit Name TEXT,
    Circuit# TEXT,
    Cable TEXT,
    Data Cable TEXT,
    Mark TEXT,
    System TEXT,
    User 1 TEXT,
    User 2 TEXT,
    User 3 TEXT,
    User 4 TEXT,
    User 5 TEXT,
    User 6 TEXT,
    User 7 TEXT,
    User 8 TEXT,
    User 9 TEXT,
    User 10 TEXT,
    User 11 TEXT,
    User 12 TEXT,
    User 13 TEXT,
    User 14 TEXT,
    User 15 TEXT,
    User 16 TEXT,
    User 17 TEXT,
    User 18 TEXT,
    User 19 TEXT,
    User 20 TEXT,
    User 21 TEXT,
    User 22 TEXT,
    User 23 TEXT,
    User 24 TEXT,
    Scenery TEXT,
    Focus L/R TEXT,
    Focus U/D TEXT,
    Focus Note TEXT,
    US TEXT,
    DS TEXT,
    SR TEXT,
    SL TEXT,
    Top TEXT,
    Bot TEXT,
    Focus Status TEXT,
    Axis TEXT,
    Beam TEXT,
    VW Layer TEXT,
    VW Label Legend TEXT,
    VW Class TEXT,
    VW X Coordinate TEXT,
    VW Y Coordinate TEXT,
    VW Z Coordinate TEXT,
    VW Symbol Rotation TEXT,
    VW Focus Point TEXT,
    Order of Light within Position TEXT,
    Lightwright ID TEXT,
    Vectorworks UID TEXT,
    Symbol TEXT,
    On Light Plot TEXT,
    Universe TEXT,
    DMX# TEXT,
    Dimmer Phase TEXT,
    Position Order TEXT,
    Work Note Status TEXT,
    Device Type TEXT,
    Color Frame TEXT,
    "When, What, and Who Changed" TEXT,
    Position & Unit# TEXT,
    Instrument Type & Accessory TEXT,
    Instrument Type & Load TEXT,
    Instrument Type & Accessory & Load TEXT,
    Circiut Name & Circuit# TEXT,
    Color & Gobo TEXT,
    Color Flags TEXT,
    DMX Qty TEXT,
    Instrument Type Weight TEXT
    )""")

    file.commit()
    file.close()
